### PR TITLE
WAZO-3683 Show Music on Hold label instead of only name

### PR DESCRIPTION
**Pull request by bloom1**
Why: since names are being autogenerated, it's hard to know what MOH to pick from the list.

### CODE REVIEW

**Comment by bloom1** [comment]
regate

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
@fblackburn1 the gate pipeline does not seem to work, that's a bit odd

**Comment by fblackburn1** [comment]
I removed `mergeit` tag since we are on freeze

**Comment by bloom1** [comment]
> I removed `mergeit` tag since we are on freeze (it will be re-added after freeze)

Totally forgot that :rofl:

**Pull request merged**
