### PR TITLE
add instance config for fixing websocket information

### PR DESCRIPTION
**Pull request by sboily**

### CODE REVIEW

**Comment by prowwid** [comment]
Thank you @sboily for pointing to his PR with  'wazo_ui.user.UserUI object' has no attribute 'get_instance_config'  issue.
I've seen the PR but didn't got that it's about the issue.

Is there any chance you can advise on when this PR will be merged? We are currently testing Wazo to see if it's a good fit for us.

**Comment by sboily** [comment]
That's a good question, i need to find time to finish to fix it, But you can use the CLI to play with modules if you need it. What would you like to do exactly?

**Comment by prowwid** [comment]
@sboily we want to test [wazo-provd-plugins](https://github.com/wazo-platform/wazo-provd-plugins).

I've installed wazo-plugind-cli and tried installing plugins using the following command:
`install git https://github.com/wazo-platform/wazo-provd-plugins.git`

But ended up with an error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xivo/cli/executor.py", line 40, in _process_next_command
    command.execute(*execute_args)
  File "/usr/lib/python3/dist-packages/wazo_plugind_cli/command.py", line 37, in execute
    self.execute_sync(*args[:-1])
  File "/usr/lib/python3/dist-packages/wazo_plugind_cli/command.py", line 55, in execute_sync
    raise Exception(last_status)
Exception: {'uuid': '48a7a6d6-7adb-41dc-b152-1dd801eb54e5', 'status': 'error', 'errors': {'error_id': 'extracting-error', 'message': 'Extracting Error', 'resource': 'plugins', 'details': {'install_options': {'ref': 'master', 'url': 'https://github.com/wazo-platform/wazo-provd-plugins.git'}}}}
```

**Comment by sboily** [comment]
This is not for the provisioning plugin. This is for creating your own plugin in the system like this module https://github.com/sboily/wazo-calld-queue. If you want to use provd, just go to the provisioning menu.

**Comment by prowwid** [comment]
@sboily thank you for clearing it up!

**Pull request merged**
