### PR TITLE
Wazo-ui: add tenant's `domain_names` field to UI

### PR DESCRIPTION
**Pull request by nissou91**

### CODE REVIEW

**Comment by pc-m** [comment]
Some parts are missing. I see no way to type in my domain names when I edit or add a tenant. And adding a new tenant displays a place to enter domain names but to input to enter the domain names.

**Comment by sboily** [comment]
It doesn't work, i have an exception. AssertionError: Field must be unbound, not a field class

**Review by pc-m — CHANGES_REQUESTED** [review]
In the edit view I do not see my domain names.
It's listed in the list view
Screenshot from 2022-05-30 14-09-54
But not in the edit view
Screenshot from 2022-05-30 14-10-03

A translation has to be added to the `domain_names` string in the edit view and I think you should remove the left side of the list where we see `Domain Names-0` and just display the domain names.

**Comment by nissou91** [comment]
> In the edit view I do not see my domain names. It's listed in the list view Screenshot from 2022-05-30 14-09-54 But not in the edit view Screenshot from 2022-05-30 14-10-03
> 
> A translation has to be added to the `domain_names` string in the edit view and I think you should remove the left side of the list where we see `Domain Names-0` and just display the domain names.

I have removed the labels of each domain from the edit tab, and also added the list of domain names of the current tenant that we are edditing, however, I did not get fully your point about translations; can you provide more details please?

**Comment by pc-m** [comment]
> The UI is very weird with the current domains on top. If I have the domain name first.com and want to add second.com I need to type first.com and second.com at the bottom otherwise first.com will disappear. The bottom list should already be filled with the current domain names when I edit the form and the top part will not be necessary

And the Domain name label on each line of the domain names list could be removed

**Review by pc-m — APPROVED** [review]

**Pull request merged**
